### ISSUE TITLE
Unbalanced crate drops

### ISSUE THREAD

**Issue by Hudeler** [svenhjol/Charm#102]
I don't know if they are intended to be that powerful, but rare crates seem very unbalanced. I opened one and got one beacon, a shulker box, two emerald blocks, an enchanted diamond chestplate with Protection III and Unbreaking III and enchanted diamond leggings with Protection III (and Curse of Rusting). Although it did spawn a few zombies and silverfish, that still seems very excessive.

**Comment by svenhjol** [comment]
In testing I haven't yet found a rare crate. If you have suggetions on how it might be balanced better I would be happy to implement a change. Loot tables for the crates can be found here: https://github.com/svenhjol/Charm/tree/master/src/main/resources/assets/charm/loot_tables/treasure

**Comment by WarlordWossman** [comment]
Oh yeah that looks like the loot is way too good :D 
I would personally remove the following items of the list entirely: Beacon, end crystal, elytra, shulkerbox, diamond block and any of the skulls.
Instead of diamond blocks just add a chance for some diamonds, then only ever have the chance for 1 enchanted golden apple but maybe add a chance for 1-3 regular golden apples, gold and diamond horse armor, maybe one of the new structure maps even and stock the rest up with enchanted books or potions rather than those endgame items you had before.

**Comment by WarlordWossman** [comment]
Maybe we should also add 2-8 clay, that sounds balanced to me.
