### ISSUE TITLE
Village Buildings on Fire

### ISSUE THREAD

**Issue by yikies** [svenhjol/Charm#13]
The majority of the time, the small village buildings spawn with one of the wood blocks on fire

**Comment by svenhjol** [comment]
Uh oh. Better get a water bucket eh

**Comment by svenhjol** [comment]
Can you send screenshot of the house that’s on fire? Also include the seed and co-ordinates of the village please. Then i will test it here

**Comment by yikies** [comment]
Going to be at work until tonight, but I can confirm that it was on multiple different worlds and in nearly every village I encountered. It always starts on the roof of the small huts and at first I thought it was spreading from the fire from the blacksmith, but it's happening even without one. It might be another mod but yours is the only one I have that edits villages. I don't have any mods that make fire spread from torches either. Can't figure it out for the life of me, but I will send screenshots when I get home tonight :) thank you!

**Comment by svenhjol** [comment]
Yeah - at first thought might have been the new fire stuff I put on the top of the blacksmith house. If you can also attach your mods that you run alongside Charm, I'll look for compatibility issues as well.

**Comment by yikies** [comment]
okay [heres](https://drive.google.com/file/d/1lU_H5Kwvm5McbplwjmZZij9NQR8rdImV/view?usp=sharing) a zip with the modlist and screenshots of a village on fire

**Comment by svenhjol** [comment]
Thank you, I'll give it a test this week

**Comment by yikies** [comment]
now heres something interesting i noticed:  all of the fires have a torch dropped in them. the only reason i found this out is bc i use the item physic mod so item drops dont burn in fire. anyway it seems as though torches are being broken during worldgen and somehow causing a fire to be placed? not sure whats causing that, none of my mods do that specifically

**Comment by svenhjol** [comment]
I've had a look at the code for item physic mod, and `updateBurn()` in `ServerPhysic.java` has this suspicious line:

https://github.com/CreativeMD/ItemPhysic/blob/65be6feb2eec0b08819838bdfb3c71fedd654862/src/main/java/com/creativemd/itemphysic/physics/ServerPhysic.java#L89

`ignitingItems` contains a torch as one of its items and it looks like this can start a fire. Because the village rendering is not perfect, there are cases where torch placement fails while village buildings are being placed, the torch can drop and this will start a fire.

If you could remove this mod from your pack and test a few villages to see if they're not burning, then you've probably identified the problem. If it is this which is causing it, you can change Charm's `Lights outside` config setting to `0.0` to prevent torches from being placed.

**Comment by yikies** [comment]
that.... is probably the culprit. I had no idea it did that, thank you so much for finding it and I'm sorry to bother you about it lol. I'll test it out tonight to be sure

**Comment by svenhjol** [comment]
It's no trouble, thanks for pointing it out. I might make it so that future versions of Charm disable the torch placement automatically if that mod is installed alongside.
