### ISSUE TITLE
Curse Break not working on curses

### ISSUE THREAD

**Issue by DamnitDevil** [svenhjol/Charm#160]
When trying to use Curse Break on a Charm curse, such as Curse of Clumsiness, it does not remove said curse. Even tried Curse Break II. No luck. 
Using 1.12.2
Survival (Tried Creative mode as well)

Have 2 videos attached to show the experience. As well as my .cfg files
[Charm Issues.zip](https://github.com/svenhjol/Charm/files/3523023/Charm.Issues.zip)

**Comment by svenhjol** [comment]
Thanks for logging this and the information so far. What version of Charm are you using?

**Comment by DamnitDevil** [comment]
1.12.2-1.1.12

**Comment by svenhjol** [comment]
I highly recommend updating to a later version. Currently, 1.3.4 is the stable release. Please try this and see if the problem continues to happen.

**Comment by svenhjol** [comment]
I still don't know what's causing this. Also there isn't "Curse Break II" so some other mod is adding this. Could you post the list of mods you're using?

**Comment by minakitty** [comment]
I'm having the issue with Charm 1.3.6 still, except mine is a Curse Break VIII.  Not sure which mod is adding all these variants (and I have a huge mod list for my pack), but I'm guessing your mod is specifically looking for "Curse Break" and not any enchanted book containing "Curse Break" in the NBT data.  For info, since I don't know how to get a proper dump of the names of mods, here's a dump of the directory of my mod folder from the server
[mods.txt](https://github.com/svenhjol/Charm/files/3767242/mods.txt)

**Comment by tyler489** [comment]
My guess is it's apotheosis as it makes enchantments exceed it's max bounties. I thought it only did it to vanilla enchants but could be wrong
