### ISSUE TITLE
[1.14.4] Music discs from the mod play at full volume no matter how far away you are

### ISSUE THREAD

**Issue by EnderdragonLord** [svenhjol/Charm#194]
When playing any of the new Charm Music Discs, they'll play at full volume even when you're thousands of blocks away. This doesn't seem to be the case for the vanilla ones, where they lose volume the farther away you're from the Jukebox.

Also, seems like the songs for both The End and the Enderdragon fight don't have their own music discs either, not sure if that was intentional or not.

**Comment by svenhjol** [comment]
Thanks for noticing this, I'll look into it for the next version.

**Comment by svenhjol** [comment]
Ok, so I'm adding the missing "End" and "Boss" music discs. However, the volume/distance issue is not something that can be easily solved because apparently the volume fade only works if the music is mono not stereo (https://www.minecraftforge.net/forum/topic/73809-solved-1144-custom-music-discs-have-unlimited-attenuation-distance/) and the original tracks by C418 are all stereo. I've tinkered with the ogg vorbis decoder in vanilla but it's probably not going to be fixed any time soon.
