### ISSUE TITLE
Nether Gold Ore (1.12.2)

### ISSUE THREAD

**Issue by Homicidal-Lemon** [svenhjol/Charm#265]
In 1.12.2, Nether Gold Ore drops a single Gold Nugget, which is worthless. This is an easy fix, but given the feature exists in a separate mod (with identical textures) it would honestly be better to straight up remove it. None of the other Charm stuff (to my knowledge) is in the Nether. Nether Gold doesn't doesn't really fit the mod, doesn't work properly, literally has another mod that does the exact same thing and is way too common. I really like Charm, but I'm considering uninstalling it because of the Nether Gold Ore. It's pointless, ugly, too common and shouldn't really even be in the mod. Rant over, but please remove it (at least for the 1.12.2 version, given that if people wanted Nether Gold, they could just add it).

**Comment by ridjack** [comment]
...you do realize that every single feature in Charm is able to be disabled in the config files, right?

Honestly, though, if this is the type of 'issue' you're likely to post in the future - making threats if a certain feature isn't removed because you personally don't like it - maybe you should just uninstall the mod. This sort of attitude is completely unhelpful.

Please don't post like this again.

**Comment by Homicidal-Lemon** [comment]
Sorry, I didn't mean to 'threatening' (but I did absolutely mean it -  I only said it to try and make my frustration evident), but I stand my reasoning that given it exists in exactly the same form but arguably better in another mod, it doesn't make sense being in Charm (at least the 1.12.2 version). Also there doesn't appear to be any config, at least not in Charm-1.12.2-1.3.7, unless I'm missing something. Below is an attached image of my apparent lack of config. https://cdn.discordapp.com/attachments/626838109962895385/712664618517921863/unknown.png

**Comment by WarlordWossman** [comment]
Yeah it has no config you can access ingame, but it doesn't mean this feature is not configurable, open the config file in your minecraft folder and change the nether gold deposits from true to false.
Also if you want to uninstall because you don't know how to configure a mod using a file, feel free to do so, mods are entirely free so nobody is interested in non constructive feedback like "do this or that or I uninstall".
