### ISSUE TITLE
[1.16.1 beta] Crash with Botania

### ISSUE THREAD

**Issue by FynnWaelsing** [svenhjol/Charm#301]
Charm version: 1.16.1-2.0.0-beta.1
Forge Version:  32.0.106
Crash log: https://pastebin.com/iKxi8bQb
Latest log: https://pastebin.com/NeRjBsfC

Added the Charm beta to my existing pack and it crashed. After some finagling in a fresh pack with just Charm, I discovered that this particular crash occurs, as the logs suggest, when installed together with Botania (1.16-399) and its dependencies.

I also posted this issue in the Botania github: https://github.com/Vazkii/Botania/issues/3388

**Comment by svenhjol** [comment]
Hey, thanks for the report. I didn't get release Charm on Curseforge as it's very fresh after the rewrite, so I'm surprised you found the build 😊

I'll run Botania locally in a dev environment and try and find the cause. Based on your logs, I'm making an assumption it's something to do with mixins, since Botania also uses them and there might be some kind of conflict.

**Comment by FynnWaelsing** [comment]
Haha, I just pulled it off the github release; been watching your progress excitedly! And yea, that seemed to be the issue, judging by the logs and what Hubry said in the Botania github issue I posted.

Looking forward to playing Charm again in 1.16!

**Comment by svenhjol** [comment]
New build coming soon now that the Botania compat is done. Thanks a lot fo the thorough report, really helped get it fixed quickly.

**Comment by FynnWaelsing** [comment]
Great! Just trying to help. Really appreciate all the work you've done in making such a great mod.

**Comment by svenhjol** [comment]
https://github.com/svenhjol/Charm/releases/download/2.0.0/Charm-1.16.1-2.0.0-beta.2.jar

:)
