### ISSUE TITLE
[1.16 Forge] Helping with the update

### ISSUE THREAD

**Issue by F43nd1r** [svenhjol/Charm#341]
I'm excited to use charm on forge 1.16.3. I know asking "when is it done" is stupid, so I'll ask a different question:
How can I help?
I know Java and have some basic experience with forge mods.

**Comment by svenhjol** [comment]
The Forge version will be a straight port of the Fabric version. Do you think you'd be able to help with that?

**Comment by F43nd1r** [comment]
I haven't worked with fabric as of yet. I'm pretty confident I could port block & item registries. Anything more complex I can probably work out over time. But as I understand it forge and fabric use very different concepts, which could make it difficult to port.

Is it possible to introduce a compatiblity layer? That would help with future updates.

**Comment by svenhjol** [comment]
Charm was originally ported from Forge, so most of the fabric events just need translating/changing. I don't want to depend on any other mods or compatibility libraries because I don't want to be held back waiting for them to update. I'm going to make a start on the Forge port after 2.1.0 is released some time next week, so I'll ping you then and let you know what needs doing. If you're still interested at that point then I'm happy for you to hack at it to speed up its development.

**Comment by svenhjol** [comment]
If you use discord I would suggest getting in touch with me there as it's easier than communicating here :)  I lurk on vazkii's discord server as svenhjol, feel free to dm
