### ISSUE TITLE
[Mod conflict] crashes with Builders blocks AND cloth-api

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#410]
Running Builders blocks and Charm without cloth-api doesn't crash. Running Builders blocks and cloth-api without Charm doesn't crash too.
Reported to [Builders blocks](https://github.com/TiphaineLAURENT/Builders-blocks/issues/9) and [cloth-api](https://github.com/shedaniel/cloth-api/issues/28) too

crash report - https://hatebin.com/wknndouhkr
latest.log - https://hatebin.com/hdgwwzanja

**Comment by svenhjol** [comment]
Hi,

Builders Blocks overwrites the vanilla RecipeManager `apply()` method with its own custom version: https://github.com/TiphaineLAURENT/Builders-blocks/blob/master/src/main/java/net/tiphainelaurent/buildersblocks/mixin/RecipesRegistrationMixin.java

Since Charm targets the default vanilla apply method to perform recipe sorting, it will always conflict. There's nothing I can do about this.
