### ISSUE TITLE
[1.17] Features to change

### ISSUE THREAD

**Issue by svenhjol** [svenhjol/Charm#496]
* Remove candles
* Remove tinted enchantment (replacement TBC)
* Acquisition enchantment rename (to discuss)
* Netherite nugget repair = Amethyst repair
* Glowballs moar light and better "splat" texture. This is going to be very important with new caves!

**Comment by svenhjol** [comment]
* Remove SleepImprovements

**Comment by Rychlas** [comment]
Greetings. 
My suggestions for the Acquisition rename: Vacuum, Siphon, Suction, 
And, yes, please remove the tinted enchantment, it appears way too often during enchanting (especially on T3). I think you could make it so that upgrading a weapon on a smithing table with a dye just changes the tint.
Thank you kindly for the awesome mod!

**Comment by svenhjol** [comment]
* Remove Crates
* Remove Portable Ender Chests

**Comment by WerDei** [comment]
Another good self-descriptive Aquisition rename could be "Pocketing"
