### ISSUE TITLE
Charm 2.3.2 Crash on Fabric 1.16.5

### ISSUE THREAD

**Issue by ribbonleaves** [svenhjol/Charm#500]
Versions
Charm version - 2.3.2
Minecraft version - 1.16.5
Fabric loader - 0.11.2
Java version - 1.8.0_281

Description
I love this mod and want to add it to my pack, but Minecraft immediately crashes (exit code -1) and I know Charm is the culprit since it's the only mod I added today. I'm using the MultiMC launcher (should be the authentic one) so I don't know why this is happening. There is no OptiFine or OptiFabric involved.

Log can be found here: https://pastebin.ubuntu.com/p/vtW48RZJqM/

**Comment by svenhjol** [comment]
Hi,

From your crash log, Charm is colliding with a mod called "Packed". They're both trying to modify the barrel constructor code. This is not code that is new to Charm (it's been present since the first build of the 1.16.x branch. There's not a lot that I can do to solve this in the short term, so I'm flagging it as a compatibility issue.

**Comment by svenhjol** [comment]
Follow up: there are mumurings of a plan to make Charm's mixins configurable via a separate config file, so it would be possible to remove this conflict mixin at the loss of variant barrels feature. It hasn't started development yet but I'll update the ticket when it does.
