### ISSUE TITLE
Crash with Heroes Expansion

### ISSUE THREAD

**Issue by BrisingrAerowing** [svenhjol/Charm#52]
[Crash Log](https://paste.dimdev.org/hirutuciyo.mccrash)

Might be on HEs end. I'll report there as well.

**Comment by svenhjol** [comment]
I downloaded and studied the code for HE. The line where it fails is this:
`this.func_175811_a(world, Blocks.field_150478_aa.func_176223_P().func_177226_a(BlockTorch.field_176596_a, EnumFacing.WEST), 13, 2, 6, box);`

The "VillageSpiderLabHouse" is trying to set the direction on what it assumes is a torch, but it's actually a stained clay block. The reason that Charm has appeared in this crashlog is because Charm intercepts all village building rendering to test if it's a vanilla house that needs to be decorated, and if it isn't vanilla it just lets it use the default rendering.

**Comment by svenhjol** [comment]
Any update on HE's end?

**Comment by BrisingrAerowing** [comment]
The particular structure that triggered the crash was split down the middle with one half two blocks higher than the other. The HE author is looking into that. I think that’s a vanilla bug, though.

**Comment by svenhjol** [comment]
If there's any feedback from HE that needs me to intervene please comment on this ticket. Marking as closed for now.

**Comment by BrisingrAerowing** [comment]
It was determined to be caused by a vanilla village generation bug. The author is going to add a few checks to guard against crashes.
