### ISSUE TITLE
Extract XP consumes the whole stack of enchanted books from the left slot

### ISSUE THREAD

**Issue by svenhjol** [svenhjol/Charm#54]

**Comment by WarlordWossman** [comment]
![extract_2](https://user-images.githubusercontent.com/16925725/58517114-92461280-81aa-11e9-9e50-5ddc02f50ac3.PNG)
![extract_1](https://user-images.githubusercontent.com/16925725/58517115-92461280-81aa-11e9-8a7b-de13c23c27de.PNG)

In beta5 the issue is kinda fixed, idk if you could solve it in a way that it takes only 1 book and gives you the bottles of enchanting. The other anvil issue seems to be resolved that way.
