### ISSUE TITLE
Charm crashing Minecraft on startup

### ISSUE THREAD

**Issue by fizzyegg** [svenhjol/Charm#544]
Recently I was playing a modpack I created with Charm added in - for no apparent reason, upon startup, Minecraft crashed. The crash log shows it stems from Charm, however it seems to not be a compatibility issue as I tested the mod in isolation and had the same issue.

Crash log is linked in the txt attached.
[crash.txt](https://github.com/svenhjol/Charm/files/6423395/crash.txt)

**Comment by BrekiTomasson** [comment]
Looks like your `charm.toml` config file might have some issues? Try deleting the config file and let the mod regenerate it.

**Comment by fizzyegg** [comment]
Did that!
Minecraft was able to start up, although joining any worlds caused this error - I don't know whether Charm is actually the source of the problem but it could be linked to the first issue.
[crash-2021-05-07_16.23.16-client.txt](https://github.com/svenhjol/Charm/files/6442705/crash-2021-05-07_16.23.16-client.txt)

**Comment by RDKRACZ** [comment]
>I don't know whether Charm is actually the source of the problem

It isn't, this is caused by an incompatibility of Fabric API 0.34 with the Cardinal Components API which is included in one of your other mods. I can see you have Origins 0.7.0 installed. To fix this crash simply update Origins (and Extraorigins etc for compatibility reasons). If your game is still crashing then you have other mods that nest some parts of CCA, not included in the Origins. You can just put the latest version of CCA to your mods folder then.
