### ISSUE TITLE
Server crash when dying with totem in hotbar

### ISSUE THREAD

**Issue by EagleTracker** [svenhjol/Charm#546]
Running into an issue. May be a conflict with the corpse mod, not sure. if i die with the totem in my off hand, everything works fine, but if i die with it in my hotbar, it kicks me and my server restarts. Not a major problem, but thought it was worth noting.

**Comment by judicius** [comment]
I'm going to add to this. I just died in a Repurposed Structures Ice Mansion. I had no totem in my inventory or on me in any way and the server crashed.

MC 1.16.5
Forge 36.1.13
Charm 2.1.9

https://gist.github.com/judicius/ae1cecdee519772081c49646dd42927c

**Comment by EagleTracker** [comment]
https://gist.github.com/EagleTracker/7c32723fee977cd155ce3f2b3a25e726

**Comment by LandonDeam** [comment]
I have the same issue as these two in a roguelike dungeons server I set up. The issue seems to be related to item deletion when using a totem from your inventory. For now I'm disabling it in the `charm.cfg` file on line 487 `UseTotemFromInventory=false`

https://gist.github.com/LandonDeam/4a45448e5538bf0793a65c5fc004adc8

**Comment by svenhjol** [comment]
Checked not happening in 1.17 client or server side, moving this to 1.16 bug fixes
