### ISSUE TITLE
Raid horn

### ISSUE THREAD

**Issue by Dismade** [svenhjol/Charm#547]
You can add Mending to raid horns. This negates the 16 durability giving you infinite uses with it.

**Comment by svenhjol** [comment]
When you register an item as taking durability damage, vanilla code automatically adds the item as a candidate for the Mending enchantment. After an internal discussion, we decided that this behavior is appropriate. It's up to the player to decide whether they want to spend the enchantment and the resulting XP on repairing the raid horn rather than outright banning it.
