### ISSUE TITLE
Loading NBT Data: malformed input around byte 646 (1.12.2)

### ISSUE THREAD

**Issue by DatrixTHLK** [svenhjol/Charm#55]
Hi,

I am getting this crash with Charm. Steps to copy this error just load up a save game for minecraft 1.12.2 and have it crash a minute later.

Minecraft: 1.12.2
Forge: 14.23.5.2838
Charm: 1.0.1

Cash Report: https://paste.dimdev.org/rebubuxato.mccrash

**Comment by svenhjol** [comment]
Line 76 of EntitySpectre doesn't do anything special. I noticed that you have some kind of mob modifier thing going on (Rough Mobs). Since EntitySpectre extends EntityZombie it might be trying to apply some behavior to Spectres that is only appropriate for Zombies, but I'm not sure. 

I did a bit of searching about this error in your crash file: `Entity's Vehicle: ~~ERROR~~ NullPointerException: null` and it seems to suggest some kind of chunk corruption. Can you try loading your level in MCEdit and navigate to `-314,34,352` - see if it reports anything unusual.

**Comment by DatrixTHLK** [comment]
I would, but I deleted it due to the game world being unplayable. If it happens again, I will let you know.

**Comment by svenhjol** [comment]
Ok thanks.
