### ISSUE TITLE
Acquisition problem

### ISSUE THREAD

**Issue by XThexLonexWolfX** [svenhjol/Charm#566]
Maybe this is how it's intended to work, but acquisition gives me the items that my friends mined even when I'm in another dimension.

**Comment by svenhjol** [comment]
This is definitely not intended! A fix has been applied to 1.17 and will be backported to 1.16. I'll let you know when there's a new jarfile to test.

**Comment by XThexLonexWolfX** [comment]
Nice! And just out of curiosity, because I was looking at the changed code. You use the position of the player to decide if the item is theirs?

**Comment by svenhjol** [comment]
It does use the mined block position to determine the player now, but there's a bit more testing to do to determine if this still causes players to pick up blocks from across dimensions, e.g. if two players were mining the exact same block position in the overworld and the end

**Comment by Pyrogeen** [comment]
Hello, I have encountered a similar issue in AOF3 modpack, a combination of range and acquisition steals all blocks anyone mines across dimensions regardless of distance.
[Here](https://github.com/TeamAOF/All-of-Fabric-3/issues/404)'s the issue from AOF3 github.
Does the fix for this bug fix the range combination issue too?
If not, should I create a new issue for this?

**Comment by Prince527GitHub** [comment]
Has this been backported to 1.16?
