### ISSUE TITLE
[1.12.2] Right-Clicking entities causes your offhand arm to swing & can break certain modded items.

### ISSUE THREAD

**Issue by Z-Tunic** [svenhjol/Charm#588]
I dunno if this is the correct place and I dunno if you still support 1.12.2, but...

Minecraft; 1.12.2
Forge: 14.23.5.2854

Mods: 2
Charm-1.12.2-1.4.1
jei_1.12.2-4.16.1.302

=====

I dunno if this is intended but if you right-click an entity... you will swing your off-hand arm which... doesn't seem to do anything. While this appeared to be a visual thing... it seems that this can cause some modded stuff to break.

"AoA3-3.3.6"
If you have Advent of Ascension installed, you will be unable to fire any of the guns that the mod offers, such as Blasters, Archerguns, Cannons, etc if you're right-clicking an entity. If Charm is removed... these weapons will work as intended.

I am currently checking to see if any other modded items break with this. Is there a way to disable the right-click off-hand swinging on entities by any chance?

I wonder if this issue might be related... unless it was fixed and then it came back or something.
https://github.com/svenhjol/Charm/issues/179

**Comment by Charles445** [comment]
This appears to be caused by the Bat Bucket feature, where your arm is swung client side due to an oversight
https://github.com/svenhjol/CharmForge/blob/1.12/src/main/java/svenhjol/charm/world/feature/BatBucket.java#L100-L102

For now, try disabling the "Bat Bucket" feature from Charm
I'll probably add something for this later
