### ISSUE TITLE
Editing signs: Text won't be saved after you quit

### ISSUE THREAD

**Issue by scorpion421** [svenhjol/Charm#594]
**Versions:**
* Charm version: 3.1.6
* Minecraft version: 1.17
* Fabric: 0.11.6
* Fabric API: 0.36.0

**Description**
`#Right-click on a sign with an empty hand to edit its text.`
You can edit signs, but after you save & quit your world and logon again, the text won't be saved, leaving you with an empty or unedited sign.

**Optional: Steps To Reproduce**
Try to edit a sign. Log off and on again and check the result.

**Optional: Stacktrace/Screenshots**
Sadly I can't provide a stacktrace or screenshot, since there is nothing to show, except the described problem.

**Comment by FynnWaelsing** [comment]
I've not been able to reproduce this issue. Can you reproduce this with just Charm installed?

**Comment by scorpion421** [comment]
Seems I have to apologize for saying, there is nothing to see. I looked in the logs after I tried to edit a sign:
[23:50:06] [Server thread/WARN]: Player MickyFoley just tried to change non-editable sign
Curious, because I don't play on a server - just SSP - so there isn't a plausible way of getting this error, I think.

**Comment by FynnWaelsing** [comment]
The "server" just refers to the internal Minecraft server, which runs even when you are playing single-player. Exactly what kind of sign were you trying to edit?

**Comment by r4j4h** [comment]
Just to follow up a friend and I are running into this as well. Replacing the signs works and it seems to not happen immediately to the signs and they remain editable for a while. But you have to know the bug happened when it does or else you make lots of sign changes and they get lost.

I just confirmed with my friend that indeed our world  started as single player and then we played via LAN before copying the files over to a server I run.

Is there any way to properly "convert" our world to end this issue?

**Comment by r4j4h** [comment]
After researching it I'm not sure what might be different between single/multiplayer actually. These are just normal signs, it does not matter if they are placed in interesting ways, standing or attached to surfaces, or attached to front of chest by holding shift when placing.

My original theory was that it was if one or the other of us placed the sign. But after upgrading from 1.17 to 1.17.1 I'm seeing it on signs I had placed. So maybe just every sign since the server upgrade? Seems odd.

Let me know if there's any more information I can provide. Otherwise the logs are just the same, ` Player <name> just tried to change non-editable sign`

We are running versions:

Charm version: 3.3.0
Minecraft version: 1.17.1 (but also happened on 1.17)
Fabric: 0.11.6
Fabric API: 0.40.1
