### ISSUE TITLE
Invalid Player Data crash when opening a world again

### ISSUE THREAD

**Issue by EnderT5** [svenhjol/Charm#634]
Versions
Charm Version: 3.3.2
Minecraft Version: 1.17.1

Description
After creating a world and quitting it, you can't join your world again.

Optional: Steps To Reproduce
Create a world, quit a world, try entering the world again. Sometimes it enters, sometimes it just crashes.

Optional: Stacktrace/Screenshots
Screenshot: https://imgur.com/a/18IpY4Y
Log: https://hastebin.com/obinajuhev.yaml

**Comment by svenhjol** [comment]
Charm currently doesn't make use of custom player data so I'm not sure what the error you're seeing is referring to.  It could be an incompatibility with another one of the mods.  If you attach your player data to this issue I can take a quick look at it in an nbt editor to see if there's anything obviously wrong.  Your player data is located here:  `saves/(your world name)/playerdata/(your player uuid).dat`

**Comment by EnderT5** [comment]
[playerdata.zip](https://github.com/svenhjol/Charm/files/6863691/playerdata.zip)

Attached the player data

**Comment by svenhjol** [comment]
There doesn't seem to be anything corrupted about yoru playerdata file. I also loaded it into a test world only containing Charm and REI and there was no error. Perhaps this is caused by another mod? You could try creating a test world yourself with Charm and see if you get an error, and if not keep adding mods until the error comes back.
