### ISSUE TITLE
trouble adding item/blocks in the "Valid books" and "Revealed blocks" setting

### ISSUE THREAD

**Issue by JonnyOnSeSocks** [svenhjol/Charm#672]
Versions
* Charm version - 3.3.2
* Minecraft version - 1.17.1

* better-nether-5.1.3
* better-end-0.11.0-pre
* xp_storage-1.4.2

Description
Im trying to add items/blocks to the bookshelf and spelunky potion options but the updated settings seem to not take effect in game. I cant place the 3 xp books in bookshelfes and the nether/end ores are not highlighted when the spelunky effect is applied.
Any help is greatly apreciated!

Steps To Reproduce
-XP storage books in bookshelf, I added this in the config.toml for [Bookcases]:
"Valid books" = ["xp_storage:xp_book", "xp_storage:xp_book2", "xp_storage:xp_book3"]

-better end and better nether ores for spelunky potion, I updated the reveal blocks setting for [PotionOfSpelunking] like this:
"Revealed blocks" = ["#minecraft:coal_ores, black", "#minecraft:iron_ores, light_gray", "#minecraft:redstone_ores, red", "#minecraft:gold_ores, yellow", "#minecraft:copper_ores, orange", "#minecraft:lapis_ores, blue", "#minecraft:diamond_ores, cyan", "#minecraft:emerald_ores, lime", "minecraft:ancient_debris, brown", "minecraft:nether_quartz_ore, light_gray", "minecraft:amethyst_block, purple", "betternether:cincinnasite_ore, yellow", "betternether:nether_ruby_ore, red", "betternether:nether_lapis_ore, blue", "betterend:ender_ore, green", "betterend:amber_ore, orange", "betterend:thallasium_ore, cyan"]

**Comment by KuysKyle3212** [comment]
Up,

**Comment by skyeblu7** [comment]
When I downloaded the source code and tried to debug it myself in IntelliJ, I found that this feature actually works for the xp_storage mod using the source code of charms. But I don't know why it doesn't work on my local minecraft launcher. I tried to create a new jar file from the source which ended up being 3.4.0 (as opposed to the most recent version on curseforge 3.3.2) but this still did not work. I noticed when launching the minecraft client from this source project, there are already mods installed: roughly enough items, mod menu, and rei-fake@ABC (not sure what this last one is). Maybe this has something to do with it? I'm not sure. Hopefully this is helpful.

**Comment by skyeblu7** [comment]
I exported a modified version of the source code that prints out the validItems list and loaded its jar file into my native launcher and found that for the items "xp_storage:xp_book", "xp_storage:xp_book2", "xp_storage:xp_book3", it was just listed as "air" when my minecraft game actually started. My guess is that the problem is that the config file is read and interpreted before the xp_storage mod is loaded.

**Comment by skyeblu7** [comment]
I tested whether the mod was loaded before the config file was read, and it is actually loaded. The problem is this section of code in src/main/java/svenhjol/charm/module/bookcases/Bookcases.java which adds to the validItems list:

'''configValidItems.forEach(string -> {
            Item item = Registry.ITEM.get(new ResourceLocation(string));
            validItems.add(item);'''

 the line 'Registry.ITEM.get(new ResourceLocation("xp_storage:xp_book")' returns 'air' for some reason.
