### ISSUE TITLE
1.18.2 slow world loading, falling into the void for several seconds until the terrain appears

### ISSUE THREAD

**Issue by MSandro** [svenhjol/Charm#776]
not sure why but after installing Charm I fall into the void for several seconds.
fabric-api-0.51.1+1.18.2
charm-fabric-1.18-4.1.0
Fabric Loader 0.14.3

**Comment by FluffyBumblee** [comment]
Same here

**Comment by dandin87** [comment]
Change this in the config. In a modded environment it can this can bring your advancements file to over 1mb. it is extremely laggy on first world join, and then every server join after since its now syncing a huge advancements file. This should never have been default True. very bad decision.
#Unlocks all vanilla recipes.
"AutomaticRecipeUnlock Enabled" = false

**Comment by FluffyBumblee** [comment]
Thank you so much!

**Comment by WarlordWossman** [comment]
a5b25f96492d11b05a4c01102b861a1f971372ea
