### ISSUE TITLE
Charm Not Working With Optifabric (1.18.2)

### ISSUE THREAD

**Issue by thetrueunrealist** [svenhjol/Charm#783]
Hi!

Whenever I boot up Charm with Optifabric, it has an exit code 1. I looked through the crash reports and it wouldnt count as a crash. It's fine when I take optifabric out. I checked and everything (my optifabric and charm) is up to date, so I don't know why it doesn't work. Also, I didn't disable anything or tampered with it. Just downloaded it, booted it up and it crashed.

**Comment by Art1xs** [comment]
Can attest

**Comment by thetrueunrealist** [comment]
what?

**Comment by Art1xs** [comment]
Can attest = This happens to me too

**Comment by thetrueunrealist** [comment]
ohh ok

**Comment by lunissa** [comment]
Kinda glad I'm not the only one having this issue. Is there any fix or ideas for this so far? All my other mods run fine as I add them back in, but the launcher crashes when loading the game when I add Charm back in. 

It also gives me the exit error 1 code and says that "This crash may be caused by an invalid Java Runtime configuration. Check any custom configuration settings."

**Comment by amarisa4321** [comment]
Yeah this is happening to me too

**Comment by Coranthes** [comment]
We do not support optifine/optifabric due to the way it breaks the game in order to make it work.
