### ISSUE TITLE
[Enhancement] Pull textures from Resource Pack

### ISSUE THREAD

**Issue by crazyirishwrencher** [svenhjol/Charm#96]
I notice the oak bookshelf chests that spawn in the village libraries have a texture that matches vanilla oak bookshelves. Any way to have these (and other appropriate items) use texture pack textures?

**Comment by svenhjol** [comment]
It doesn’t pull from textures, but you can override the default textures if you like. There is one for each “slot” of the bookshelf as it is filled. I’ll post back here with the filenames.

**Comment by svenhjol** [comment]
`charm/blocks/bookshelf_chest_X.png` where `X` is a number between 0-9 inclusive, representing each state of the filled slots. I'm intending to add variants soon(TM) for each type of vanilla wood, so that might cause a problem with texture pack theming. If I remember I'll update you on this ticket when that happens. Thanks!
